config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "turdles#index"

  resource :turdle
end

app/models/animal.rb
# frozen_string_literal: true

# t.string "name"
# t.integer "weight"
# t.integer "height"
# t.integer "lifespan"
# t.integer "gestation"
class Animal < ApplicationRecord
  has_many :games
  has_many :guesses

  enum diet: %i[meat omni herb]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/game.rb
# frozen_string_literal: true

# Turdle game data and logic
class Game < ApplicationRecord
  belongs_to :animal

  %i[guess_one guess_two guess_three guess_four guess_five guess_six].each do |sym|
    belongs_to sym, class_name: "Animal", optional: true
  end

  attr_accessor :guess

  # first records the guess passed in, then checks it and updates the
  # game accordingly. game is won if it matches, otherwise the round
  # incremented by one.
  #
  # @param guess [Animal] Animal submitted by the select.
  def check_guess(guess)
    record_guess(guess)

    if round_to_guess == animal
      update(won: true)
    else
      update(round: round + 1)
    end
  end

  def guesses
    (1..6).map { |i| new_guess(i) }
  end

  private

  def new_guess(int)
    Guess.new(round_to_guess(int), animal)
  end

  def record_guess(guess)
    case round
    when 1 then update(guess_one: guess)
    when 2 then update(guess_two: guess)
    when 3 then update(guess_three: guess)
    when 4 then update(guess_four: guess)
    when 5 then update(guess_five: guess)
    when 6 then update(guess_six: guess)
    end
  end

  def round_to_guess(int = round)
    case int
    when 1 then guess_one
    when 2 then guess_two
    when 3 then guess_three
    when 4 then guess_four
    when 5 then guess_five
    when 6 then guess_six
    end
  end
end

app/models/guess.rb
# frozen_string_literal: true

# In memory model representing a guess
class Guess
  attr_reader :guess, :answer

  # @param answer [Guess]
  def initialize(guess, answer)
    @guess = guess
    @answer = answer
  end

  def pending?
    guess.nil?
  end

  def correct?
    guess == answer
  end

  def diet
    guess.diet
  end

  def diet_correct?
    guess.diet == answer.diet
  end

  %i[weight height lifespan gestation].each do |sym|
    define_method("#{sym}_difference".to_sym) do
      guess.send(sym) - answer.send(sym)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/turdles_controller.rb
# frozen_string_literal: true

# main entry for the app
class TurdlesController < ApplicationController
  before_action :check_new_game, :find_or_create_game

  def create
    @game.check_guess(guessed_animal)

    respond_to do |format|
      format.html { redirect_to root_path, notice: "moo" }
      format.turbo_stream
    end
  end

  private

  # @return [Game]
  def find_or_create_game
    return @game = Game.find(session[:game]["id"]) if session[:game]

    @game = Game.create(animal: Animal.all.sample, round: 1)
    session[:game] = @game
  end

  # @return [Animal]
  def guessed_animal
    @guessed_animal ||= Animal.find(params.dig("game", "guess").to_i)
  end

  def check_new_game
    reset_session if params["reset"]
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

# Foo
module ApplicationHelper
  def animal_options
    options_for_select(Animal.all.map { |animal| [animal.name, animal.id] })
  end

  BOX_CLASSES = %w[border-solid h-14 w-14 border-2 border-gray-300 text-center].freeze
  UP_ARROW = "↑"
  DOWN_ARROW = "↓"

  # @param guess [Guess]
  def guess_box(guess, field)
    classes = case field
              when :diet
                [*BOX_CLASSES, diet_bg(guess)]
              else
                [*BOX_CLASSES, guess_bg(guess, field)]
              end

    content_tag(:div, content(guess, field), class: classes.join(" "))
  end

  def content(guess, field)
    return if guess.pending?
    return guess.diet if field.equal?(:diet)

    diff = guess.send("#{field}_difference")
    arrow = diff.positive? ? DOWN_ARROW : UP_ARROW
    arrow = "✯" if diff.zero?

    [diff, arrow].join("<br/>").html_safe
  end

  def diet_bg(guess)
    return if guess.pending?
    return "bg-green-500" if guess.diet_correct?

    "bg-red-500"
  end

  def guess_bg(guess, field)
    return if guess.pending?

    diff = guess.send("#{field}_difference")
    return "bg-green-500" if diff.zero?

    "bg-yellow-500"
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Turdle</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>

app/views/turdles/_form.erb
<%# app/views/turdles/_form.html.erb %>

<%= form_for game, url: turdle_path, method: :post, html: { class: "flex justify-around" }, format: :turbo_stream do |f| %>
  <%= f.number_field :id, {hidden: true} %>
  <%= f.select :guess, animal_options, input_html: { autofocus: true } %>
  <button class="rounded-md px-5 py-2 bg-blue-600 text-white font-medium">
    <%= f.submit "Guess"%>
  </button>
<% end %>

app/views/turdles/_guess.erb
<div class="grid grid-cols-5 mx-auto gap-2">
  <%= guess_box(guess, :diet)      %>
  <%= guess_box(guess, :height)    %>
  <%= guess_box(guess, :weight)    %>
  <%= guess_box(guess, :lifespan)  %>
  <%= guess_box(guess, :gestation) %>
</div>

app/views/turdles/create.turbo_stream.erb
<%=
  turbo_stream.update "guesses",
  partial: "guess",
  collection: @game.guesses
%>

<%= turbo_stream.update "endgame" do %>
  <% if @game.won %>
    You win!
  <% elsif @game.round > 6 %>
    You lose.
  <% end %>
<% end %>

app/views/turdles/index.erb
<div class="grid grid-cols-1 gap-4 mx-auto justify-items-center mt-2">
  <div class="container flex place-items-center">
    <div class="w-1/3 text-left">💩</div>
    <div class="font-serif text-2xl text-black w-1/3 text-center">
      <h1>Turdle</h1>
    </div>

    <div class="text-sm text-right w-1/3"> <%= link_to "NEW", "/?reset=true" %> </div>
  </div>

  <div class="shrink-0 flex-grow">
    <img class="aspect-square" src="/assets/turd.jpg" alt="Turdle">
  </div>

  <div id="turdle-form" class="container">
    <%= render "form", game: @game %>
  </div>

  <div class="grid grid-cols-5 mx-auto justify-items-center text-center">
    <p>Diet</p> <p>Weight</p> <p>Height</p> <p>Life</p> <p>Gestation</p>
  </div>

  <div id="guesses" class="container grid grid-rows-6 gap-2">
    <%= render partial: "guess", collection: @game.guesses %>
  </div>

  <div id="endgame" class=""></div>

</div>

app/views/turdles/old-index.erb
<div class="flex flex-col mx-auto space-y-6 items-center content-center h-36">
  <div class="flex-1 font-serif text-xl text-black h-8">
    <h1>Turdle</h1>
  </div>

  <div class="flex-1 shrink-0 flex-grow">
    <img class="flex-1 w-full aspect-square" src="/assets/turd.jpg" alt="Turdle">
  </div>

  <div id="turdle-form" class="flex-1 flex-grow">
    <%= render "form", game: @game %>
    <%= link_to "New Game", "/?reset=true" %>
  </div>

  <div id="guesses" class="flex-1 flex-grow"></div>
  <div id="endgame" class="flex-1 flex-grow"></div>
</div>